repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  -   id: end-of-file-fixer
  -   id: trailing-whitespace

- repo: local
  hooks:
    - id: build mishell
      name: build mishell
      entry: bash -c 'make mishell'
      language: system
      pass_filenames: false
    - id: build mishli
      name: build mishli
      entry: bash -c 'make mishli'
      language: system
      pass_filenames: false
    - id: unit-test
      name: unit-test
      entry: bash -c 'make test-unit'
      language: system
      pass_filenames: false
