name: Mishell CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install nasm
        run: sudo apt-get update && sudo apt-get install -y nasm

      - name: mishell and mishli build
        run: make

      - name: Run e2e tests
        run: |
          make run-init &
          make test-e2e

  test-unit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite:
          - unit/src/host
          - unit/src/op
          - unit/src/packet
          - unit/lib/string
          - unit/lib/net
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install nasm
        run: sudo apt-get update && sudo apt-get install -y nasm
      - name: Run ${{ matrix.suite }} tests
        working-directory: tests/${{ matrix.suite }}
        run: make
