name: Mishell CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mishell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install nasm
        run: sudo apt-get update && sudo apt-get install -y nasm

      - name: mishell builds
        run: make

  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install nasm
        run: sudo apt-get update && sudo apt-get install -y nasm

      - name: mishell builds
        run: make

      - name: Run mishell
        run: |
          make run-init &
          echo $! > server.pid
          sleep 1

      - name: Run python client script
        run: make test-e2e

  test-unit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite:
          - unit/src/auth
          - unit/src/host
          - unit/lib/string
          - unit/lib/net
    steps:
      - uses: actions/checkout@v4
      - name: Install nasm
        run: sudo apt-get update && sudo apt-get install -y nasm
      - name: Run ${{ matrix.suite }} tests
        working-directory: tests/${{ matrix.suite }}
        run: make
